#!/bin/bash

echo "🧹 Ressources à supprimer manuellement via AWS Console:"
echo ""
echo "1. Lambda Functions:"
echo "   https://eu-west-1.console.aws.amazon.com/lambda"
echo "   → Supprimer: borne-appetit-health"
echo ""
echo "2. API Gateway:"
echo "   https://eu-west-1.console.aws.amazon.com/apigateway"
echo "   → Supprimer: borne-appetit-api"
echo ""
echo "3. CloudFront:"
echo "   https://console.aws.amazon.com/cloudfront"
echo "   → Désactiver puis supprimer les distributions"
echo ""
echo "4. S3 Buckets:"
echo "   https://s3.console.aws.amazon.com/s3"
echo "   → Vider puis supprimer: borne-appetit-assets"
echo ""
echo "5. DynamoDB:"
echo "   https://eu-west-1.console.aws.amazon.com/dynamodbv2"
echo "   → Supprimer: borne-appetit-table, borne-appetit-config"
echo ""
echo "6. IAM Roles:"
echo "   https://console.aws.amazon.com/iam"
echo "   → Supprimer: borne-appetit-lambda-role"
echo ""
echo "Après nettoyage, relancez: cd app/tf && terraform apply"
